Enhance display of macOS version
Whenever a specific macOS version is displayed, the correct prefix
(e.g. 'Mac OS X' or 'macOS') and its marketing name (e.g. High Sierra)
is used.

diff --git a/createinstalliso b/createinstalliso
--- a/createinstalliso
+++ b/createinstalliso
@@ -60,6 +60,25 @@ declare -r -a const_supported_installer_application_display_names=(
 	"Install macOS Sierra"       # 10.12
 )
 
+declare -r -a const_macos_names=(
+	"Mac OS X Cheetah"      # 10.0 "Cheetah"
+	"Mac OS X Puma"         # 10.1 "Puma"
+	"Mac OS X Jaguar"       # 10.2 "Jaguar"
+	"Mac OS X Panther"      # 10.3 "Panther"
+	"Mac OS X Tiger"        # 10.4 "Tiger"
+	"Mac OS X Leopard"      # 10.5 "Leopard"
+	"Mac OS X Snow Leopard" # 10.6 "Snow Leopard"
+	"Mac OS X Lion"         # 10.7 "Lion"
+	"OS X Mountain Lion"    # 10.8 "Mountain Lion"
+	"OS X Mavericks"        # 10.9 "Mavericks"
+	"OS X Yosemite"         # 10.10 "Yosemite"
+	"OS X El Capitan"       # 10.11 "El Capitan"
+	"macOS Sierra"          # 10.12 "Sierra"
+	"macOS High Sierra"     # 10.13 "High Sierra"
+	"macOS Mojave"          # 10.14 "Mojave"
+	"macOS Catalina"        # 10.15 "Catalina"
+)
+
 unset global_exit_message
 unset global_tmp_directory
 unset global_install_media_device_node
@@ -294,7 +313,9 @@ is_valid_installer_application_path() {
 
 	case "${installer_application_type}" in
 
-		# '1' - Installer application type for macOS 10.7 to 10.8
+		# '1' - Installer application type for:
+		# - Mac OS X Lion 10.7
+		# - OS X Mountain Lion 10.8
 		1 )
 			# This file is required because it will be used as source
 			# to create the installer disk image.
@@ -303,7 +324,10 @@ is_valid_installer_application_path() {
 			return 0
 			;;
 
-		# '2' - Installer application type for macOS 10.9 to 10.11
+		# '2' - Installer application type for:
+		# - OS X Mavericks 10.9
+		# - OS X Yosemite 10.10
+		# - OS X El Capitan 10.11
 		2 )
 			# Apple's command 'createinstallmedia' is required because
 			# it will be used to create the installer disk image.
@@ -328,7 +352,10 @@ is_valid_installer_application_path() {
 			return 0
 			;;
 
-		# '3' - Installer application type for macOS 10.12 to 10.13
+		# '3' - Installer application type for:
+		# - macOS Sierra 10.12
+		# - macOS High Sierra 10.13
+		# - macOS Mojave 10.14
 		3 )
 			# Apple's command 'createinstallmedia' is required because
 			# it will be used to create the installer disk image.
@@ -476,6 +503,33 @@ get_os_name() {
 	os_name="$(uname -s 2> /dev/null)" || return 1
 
 	echo "${os_name}"
+	return 0
+}
+
+create_macos_name_and_version() {
+	local -r -i macos_minor_version="${1:-0}"
+	local -r -i macos_patch_version="${2:-0}"
+	local -i largest_known_macos_minor_version="${#const_macos_names[@]}"
+	local macos_name="macOS"
+	local macos_version
+
+	(( --largest_known_macos_minor_version ))
+
+	if (( macos_minor_version < 0 || macos_patch_version < 0 )); then
+		return 1
+	fi
+
+	if (( macos_minor_version <= largest_known_macos_minor_version )); then
+		macos_name="${const_macos_names[${macos_minor_version}]}"
+	fi
+
+	if (( macos_patch_version > 0 )); then
+		macos_version="10.${macos_minor_version}.${macos_patch_version}"
+	else
+		macos_version="10.${macos_minor_version}"
+	fi
+
+	echo "${macos_name} ${macos_version}"
 	return 0
 }
 
@@ -641,10 +695,18 @@ get_example_installer_application_name() {
 #
 # The returned types are:
 #
-# '0' - Installer application type unknown
-# '1' - Installer application type for macOS 10.7 to 10.8
-# '2' - Installer application type for macOS 10.9 to 10.11
-# '3' - Installer application type for macOS 10.12 to 10.13
+# '0' = Installer application type unknown
+# '1' = Installer application type for:
+#       - Mac OS X Lion 10.7
+#       - OS X Mountain Lion 10.8
+# '2' = Installer application type for:
+#       - OS X Mavericks 10.9
+#       - OS X Yosemite 10.10
+#       - OS X El Capitan 10.11
+# '3' = Installer application type for:
+#       - macOS Sierra 10.12
+#       - macOS High Sierra 10.13
+#       - macOS Mojave 10.14
 #
 # Input:
 # $1 - path to the installer application
@@ -932,6 +994,7 @@ main() {
 	local -i macos_minor_version
 	local -i macos_patch_version
 	local -i macos_version_for_compare
+	local macos_name_and_version
 
 	os_name="$(get_os_name)" || exit_with_error "Couldn't get operating system name."
 
@@ -942,18 +1005,20 @@ main() {
 
 	macos_version_string="$(sw_vers -productVersion 2> /dev/null)" || exit_with_error "Couldn't get macOS version."
 	IFS='.' read -r -a macos_version < <(echo "${macos_version_string}") || exit_with_error "Couldn't get macOS version."
-	macos_major_version="${macos_version[0]:-"0"}"
-	macos_minor_version="${macos_version[1]:-"0"}"
-	macos_patch_version="${macos_version[2]:-"0"}"
+	macos_major_version="${macos_version[0]:-0}"
+	macos_minor_version="${macos_version[1]:-0}"
+	macos_patch_version="${macos_version[2]:-0}"
 	(( macos_version_for_compare = (macos_major_version * 10000) + (macos_minor_version * 100) + macos_patch_version ))
 
 	if is_unsupported_macos_minor_version "${macos_minor_version}"; then
-		echo_error "This tool requires macOS 10.${const_supported_macos_minor_versions[0]} or later."
+		macos_name_and_version="$(create_macos_name_and_version "${const_supported_macos_minor_versions[0]}")" || exit_with_error "Invalid macOS version."
+		echo_error "This tool requires ${macos_name_and_version} or later."
 		exit 1
 	fi
 
 	if ! is_supported_macos_minor_version "${macos_minor_version}"; then
-		echo_warning "This tool has not been tested on macOS ${macos_major_version}.${macos_minor_version}.${macos_patch_version}"
+		macos_name_and_version="$(create_macos_name_and_version "${macos_minor_version}" "${macos_patch_version}")" || exit_with_error "Invalid macOS version."
+		echo_warning "This tool has not been tested on ${macos_name_and_version}."
 	fi
 
 	# ==================================================================
@@ -1136,14 +1201,16 @@ main() {
 
 	if [[ "${installer_application_type}" == "3" ]]; then
 		installer_minimum_macos_version_string="$(get_installer_minimum_macos_version "${installer_application_path}")" || exit_with_error "Couldn't get minimum macOS version for installer application."
-		IFS='.' read -r -a macos_version < <(echo "${installer_minimum_macos_version_string}") || exit_with_error "Couldn't get minimum macOS version for installer application."
-		installer_minimum_macos_major_version="${installer_minimum_macos_version[0]:-"0"}"
-		installer_minimum_macos_minor_version="${installer_minimum_macos_version[1]:-"0"}"
-		installer_minimum_macos_patch_version="${installer_minimum_macos_version[2]:-"0"}"
+		IFS='.' read -r -a installer_minimum_macos_version < <(echo "${installer_minimum_macos_version_string}") || exit_with_error "Couldn't get minimum macOS version for installer application."
+		installer_minimum_macos_major_version="${installer_minimum_macos_version[0]:-0}"
+		installer_minimum_macos_minor_version="${installer_minimum_macos_version[1]:-0}"
+		installer_minimum_macos_patch_version="${installer_minimum_macos_version[2]:-0}"
 		(( installer_minimum_macos_version_for_compare = (installer_minimum_macos_major_version * 10000) + (installer_minimum_macos_minor_version * 100) + installer_minimum_macos_patch_version ))
 
-		if (( installer_minimum_macos_version_for_compare < macos_version_for_compare )); then
-			echo_error "Creating an ISO image from this installer application requires macOS ${installer_minimum_macos_version_string} or later."
+		if (( installer_minimum_macos_version_for_compare > macos_version_for_compare )); then
+			macos_name_and_version="$(create_macos_name_and_version "${installer_minimum_macos_minor_version}" "${installer_minimum_macos_patch_version}")" || exit_with_error "Invalid macOS version."
+#			echo_error "Creating an ISO image from this installer application requires ${macos_name_and_version} or later."
+			echo_error "You need ${macos_name_and_version} or later to create an ISO image from this installer application."
 			exit 1
 		fi
 	fi
@@ -1192,16 +1259,24 @@ main() {
 
 	case "${installer_application_type}" in
 
-		# '1' - Installer application type for macOS 10.7 to 10.8
+		# '1' - Installer application type for:
+		# - Mac OS X Lion 10.7
+		# - OS X Mountain Lion 10.8
 		1 )
 			iso_source_image="${installer_application_path}/Contents/SharedSupport/InstallESD.dmg"
 			;;
 
-		# '2' - Installer application type for macOS 10.9 to 10.11
+		# '2' - Installer application type for:
+		# - OS X Mavericks 10.9
+		# - OS X Yosemite 10.10
+		# - OS X El Capitan 10.11
 		2 )
 			;;
 
-		# '3' - Installer application type for macOS 10.12 to 10.13
+		# '3' - Installer application type for:
+		# - macOS Sierra 10.12
+		# - macOS High Sierra 10.13
+		# - macOS Mojave 10.14
 		3 )
 			echo "Creating disk image..."
 			install_media_target_image="${global_tmp_directory}/InstallMedia.sparseimage"
